name: chance
version: 1.0.0
description: A minimalist generator of random numbers - inspired by chance.js
homepage: https://github.com/blausoft/chance

environment:
  sdk: '>=1.12.0 <3.0.0'

dev_dependencies:
  test: '^1.3.0'
